name: Build and Deploy iOS App to App Center

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Xcode environment
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    # Step 3: Build the iOS app
    - name: Build iOS App
      run: xcodebuild -workspace TestCI.xcworkspace -scheme MyApp -sdk iphoneos -configuration Release archive -archivePath $PWD/build/TestCI.xcarchive

    # Step 4: Export the IPA file
    - name: Export IPA
      run: xcodebuild -exportArchive -archivePath $PWD/build/TestCI.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build/

    # Step 5: Upload the IPA to App Center
    - name: Upload IPA to App Center
      uses: microsoft/appcenter-upload-action@v1
      with:
        appcenter_api_token: ${{ secrets.APPCENTER_API_TOKEN }} # Use the App Center token stored in GitHub Secrets
        owner_name: 'Nackyr'    # Replace with your App Center owner name
        app_name: 'TestCI'        # Replace with your App Center app name
        app_path: build/TestCI.ipa               # Path to the IPA file
        distribution_group: 'Collaborators'     # Distribution group
