name: Build and Deploy iOS App to App Center

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: List Directory Contents to verify path
    - name: List Directory Contents
      run: ls -R

    # Step 3: Set up Xcode environment
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    # Step 4: Build the iOS app for the simulator
    - name: Build iOS App (Simulator)
      run: xcodebuild -project TestCI/TestCI.xcodeproj -scheme TestCI -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' build CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY=""

    # Step 5: Export the IPA file using the correct path to exportOptions.plist
    - name: Export IPA
      run: xcodebuild -exportArchive -archivePath $PWD/build/TestCI.xcarchive -exportOptionsPlist TestCI/TestCI/exportOptions.plist -exportPath $PWD/build/

    # Step 6: Install App Center CLI
    - name: Install App Center CLI
      run: npm install -g appcenter-cli

    # Step 7: Upload the IPA to App Center using the CLI
    - name: Upload IPA to App Center
      run: appcenter distribute release \
            --app "Nackyr/TestCI" \
            --file build/TestCI.ipa \
            --group Collaborators \
            --token ${{ secrets.APPCENTER_API_TOKEN }}
